\begin{minted}{text}
ESEMPIO:
'''Titolo''' La partigiana Rosani e il benefattore Forti, il rabbino: «Preghiamo per la pace globale, finisca il dolore di tutti»
'''Sottotitolo''' Le parole del rabbino Corinaldi al cimitero ebraico in occasione della commemorazione di Achille Forti e Rita Rosani e dell'avvio del Yom Kippur, il giorno dell'espiazione.
'''Corpo''' «Stiamo vivendo momenti importanti, che speriamo possano cambiare la situazione e portare a un nuovo anno migliore di quelli vissuti negli ultimi due. 
Oggi preghiamo per il popolo ebraico ma anche per tutto il mondo, a cui vogliamo bene. 
Cerchiamo di vivere in serenità, in pace».
Le parole sono del rabbino di Verona, Tomer Corinaldi, pronunciate al cimitero ebraico, in occasione della commemorazione del benefattore del Comune di Verona, Achille Forti, e della Medaglia d’oro Rita Rosani.
Oggi iniziano le 25 ore di digiuno totale e di preghiera per gli ebrei, in occasione dello Yom Kippur, il giorno dell’espiazione.
«Confidiamo che potremo forse raggiungere la pace nella terra di Israele e per il popolo palestinese. 
Preghiamo per assicurare la sicurezza di tutti gli abitanti della terra. 
Gli ostaggi che stanno nel tunnel di Gaza da oltre due anni potrebbero finalmente tornare a casa, continueremo a pregare perché ciò avvenga e per la pace globale, perché finisca questo dolore di tutti».
Alla cerimonia è intervenuto anche l’assessore ai diritti umani, Jacopo Buffolo, ricordando il benefattore della città, Achille Forti, a cui è riservato spazio anche nella mostra ancora in corso a Castelvecchio, e la partigiana triestina Rita Rosani, caduta sui nostri monti. 
«Rita come molte altre ragazze è caduta per la libertà e la pace”, ha detto Buffolo, “ciò a cui dobbiamo rivolgere principalmente la mente in questo momento».
«Le 25 ore di digiuno non sono lo scopo principale dello Yom Kippur, che è piuttosto un invito alla riflessione e al ripensamento della nostra vita», è intervenuta la vicepresidente della comunità ebraica, Ester Silvana Israel.
«Il nostro augurio è di una pace giusta e duratura».
'''YAML'''
```
ner:
    persona:
    - Tomer Corinaldi
    - Achille Forti
    - Rita Rosani
    - Jacopo Buffolo
    - Ester Silvana Israel
    luogo:
    - Verona
    - Castelvecchio
    - Israele
    - Gaza
    festività:
    - Yom Kippur
    data:
    organizzazione:
    orari:
    valuta:
    percentuale:
    quantità:
    -25 ore
```
...
\end{minted}