\begin{minted}{text}
Dammi una definizione del termine <lemma>, come riporterebbe un dizionario.
La risposta deve essere restituita seguendo il formato:
    '''lemma scritto in maiuscolo e grassetto'''.
    Nella sua forma comune, '''definizione in stile formale e conciso'''.
    Esempi di utilizzo: '''esempi di utilizzo nella forma comune'''.
    Alcune accezioni: '''accezioni con esempi'''.
\end{minted}